# SPDX-FileCopyrightText: 2026 James Harton
#
# SPDX-License-Identifier: Apache-2.0

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  CI:
    uses: beam-bots/.github/.github/workflows/zola-ci.yml@4f3efeee51fbb99037d0d06423f2e84a5cbabcc7 # main
    with:
      enable-deploy: ${{ github.ref == 'refs/heads/main' }}
