# SPDX-FileCopyrightText: 2026 James Harton
#
# SPDX-License-Identifier: Apache-2.0

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  CI:
    uses: beam-bots/.github/.github/workflows/zola-ci.yml@ea14ecfba98c3efb2f8a85d75fabc4c9d7d38c1a # main
    with:
      enable-deploy: ${{ github.ref == 'refs/heads/main' }}
