# SPDX-FileCopyrightText: 2026 James Harton
#
# SPDX-License-Identifier: Apache-2.0

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  CI:
    uses: beam-bots/.github/.github/workflows/zola-ci.yml@41f7de3f701dfd06440c6f28262d0870b0c4753b # main
    with:
      enable-deploy: ${{ github.ref == 'refs/heads/main' }}
